name: API Tests
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Npm Install
        run: npm ci
      - name: Secret
        run: echo "${{secrets.API_KEY}}"
      - name: Run Tests
        run: npm run test
        env:
          API_KEY: ${{secrets.API_KEY}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}


